In [1]:
# 1
import numpy as np


print(np.__version__)

1.26.4


In [2]:
# 2
import pandas as pd
df = pd.read_csv('it_services_tickets_raw.csv')
hours = pd.to_numeric(
    df["hours_logged"].astype(str).str.extract(r"([-+]?\d*\.?\d+)")[0],
    errors="coerce"
).to_numpy()
print(hours)

[ nan 1.34 7.   ... 5.   2.   6.5 ]


In [3]:
#3
print("Shape:", hours.shape)
print("Size:", hours.size)
print("Dtype:", hours.dtype)

Shape: (49588,)
Size: 49588
Dtype: float64


In [4]:
#4
arr = np.arange(1, 51)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]


In [5]:
#5
print(np.linspace(0, 100, 10))

[  0.          11.11111111  22.22222222  33.33333333  44.44444444
  55.55555556  66.66666667  77.77777778  88.88888889 100.        ]


In [6]:
#6
print("Array with 10 zeros: ",np.zeros(10))
print("Array with 10 ones: " ,np.ones(10))

Array with 10 zeros:  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Array with 10 ones:  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [7]:
#7
np.random.seed(42)
print(np.random.rand(3, 3))

[[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]]


In [8]:
# 8
rates = pd.to_numeric(
    df["Billing Rate (USD)"].astype(str).str.replace(",", "", regex=False).str.extract(r"([-+]?\d*\.?\d+)")[0],
    errors="coerce"
).to_numpy()
twoDimArray = np.column_stack((hours, rates))
print(twoDimArray)

[[   nan  39.45]
 [  1.34  33.15]
 [  7.    48.1 ]
 ...
 [  5.    24.94]
 [  2.   116.76]
 [  6.5   89.02]]


In [9]:
# 9
print(twoDimArray.ndim)
print(hours.ndim)

2
1


In [10]:
# 10
print(hours[:5])

[  nan  1.34  7.   34.63 12.76]


In [11]:
# 11
print(hours[-5:])

[ 4.  47.   5.   2.   6.5]


In [12]:
# 12
print(hours[:20:2])

[   nan   7.    12.76    nan   1.66    nan  11.63  28.     0.59 253.85]


In [13]:
# 13
print(hours[::-1])

[6.5  2.   5.   ... 7.   1.34  nan]


In [14]:
# 14
print(np.nansum(hours))

2922291.6999999997


In [15]:
# 15
hours = np.asarray(hours, dtype=float)

print("Mean:", np.nanmean(hours))
print("Min:", np.nanmin(hours))
print("Max:", np.nanmax(hours))

Mean: 62.750519647841955
Min: -12.5
Max: 9888.01


In [16]:
# 16
print(np.std(hours))

nan


In [17]:
# 17
hours = pd.to_numeric(pd.Series(hours), errors="coerce").to_numpy()
print(np.nanmedian(hours))

13.125


In [18]:
# 18
print(np.isnan(hours).sum())

3018


In [19]:
# 19
print(np.nanmean(hours))

62.750519647841955


In [20]:
# 20
hours_filled = np.nan_to_num(hours, nan=0.0)
print(hours_filled)

[0.   1.34 7.   ... 5.   2.   6.5 ]


In [21]:
# 21
print((hours > 100).sum())

2052


In [22]:
# 22
print(hours[hours > 100])

[253.85 541.3  128.   ... 562.22 141.9  137.56]


In [23]:
# 23
print(hours[(hours > 10) & (hours < 50)])

[34.63 12.76 15.3  ... 19.   25.23 47.  ]


In [24]:
# 24
print((hours<0).sum())

191


In [25]:
# 25
hours[hours<0]=0
print(hours)

[ nan 1.34 7.   ... 5.   2.   6.5 ]


In [26]:
# 26
print(np.sort(hours))

[ 0.  0.  0. ... nan nan nan]


In [27]:
# 27
print(np.nanargmax(hours))

10080


In [28]:
# 28
np.sort(hours[~np.isnan(hours)])[::-1][:5]

array([9888.01, 9888.01, 8760.  , 8760.  , 8760.  ])

In [29]:
# 29
print(np.round(hours,1))

[nan 1.3 7.  ... 5.  2.  6.5]


In [30]:
# 30
print(hours*2)

[  nan  2.68 14.   ... 10.    4.   13.  ]


In [31]:
# 31
print(hours+10)

[  nan 11.34 17.   ... 15.   12.   16.5 ]


In [32]:
# 32
print(hours * rates)

[    nan  44.421 336.7   ... 124.7   233.52  578.63 ]


In [33]:
# 33
print(len(hours) == len(rates))
print(hours.shape == rates.shape)

True
True


In [34]:
# 34
print(len(hours) == len(rates))
print(hours.shape == rates.shape)

True
True


In [35]:
# 35
speed = np.where(hours >24, "slow","fast")
print(speed)

['fast' 'fast' 'fast' ... 'fast' 'fast' 'fast']


In [36]:
# 36
priority = df["PRIORITY"].fillna("Unknown").to_numpy()
print(np.unique(priority))

[' ' '-' '--' '1' '2' '3' '4' '?' 'CRITICAL' 'Critical' 'HIGH' 'High'
 'LOW' 'Low' 'MEDIUM' 'Medium' 'P1' 'P1 - Critical' 'P2' 'P3' 'P4'
 'PRIORITY' 'Unknown' 'high' 'low' 'medium' 'missing' 'na' 'p1' 'p2' 'p3'
 'p4']


In [37]:
# 37
values, counts = np.unique(priority, return_counts=True)
print(values, counts)

[' ' '-' '--' '1' '2' '3' '4' '?' 'CRITICAL' 'Critical' 'HIGH' 'High'
 'LOW' 'Low' 'MEDIUM' 'Medium' 'P1' 'P1 - Critical' 'P2' 'P3' 'P4'
 'PRIORITY' 'Unknown' 'high' 'low' 'medium' 'missing' 'na' 'p1' 'p2' 'p3'
 'p4'] [  97  108  111 1992 2019 1995 1968   90 2047 2063 2005 2059 2002 1900
 2013 2015 1945 2044 1967 2010 1930    4  856 2029 2003 2072  128  132
 1993 1961 2069 1961]


In [38]:
# 38
grid = hours[:100].reshape(10, 10)
print(grid.shape)

(10, 10)


In [39]:
# 39
print(grid.T)

[[        nan         nan 5.08100e+01 1.80000e+01 2.90000e+00 1.12600e+01
  1.90066e+03 2.05100e+01 1.91700e+01 1.30000e+01]
 [1.34000e+00 1.44000e+00 8.01000e+00 3.14400e+01 3.92000e+00 2.40000e+01
  4.00000e+00 1.13300e+01 1.78600e+01 1.09100e+01]
 [7.00000e+00 1.16300e+01 6.79400e+01 3.42000e+00 2.02200e+01 5.26000e+00
  3.00000e+00 5.99100e+01 9.21000e+00 8.00000e+00]
 [3.46300e+01 7.23100e+01         nan 2.44600e+01 2.41500e+01 1.40000e+01
  9.00000e+00 1.00000e+00 5.40000e+01 3.81000e+00]
 [1.27600e+01 2.80000e+01 3.27100e+01 3.90000e+01 8.40000e+01 5.00000e+00
  1.33350e+02 2.29700e+01         nan 3.73680e+02]
 [1.53000e+01 1.01600e+01 5.41300e+02 1.30000e+01         nan 1.14100e+01
  1.29170e+03 0.00000e+00 2.00000e+01 1.13800e+01]
 [        nan 5.90000e-01 6.91000e+00 3.00200e+01 2.70000e+01         nan
  4.00000e+00 2.49000e+01 6.00000e+00 3.36700e+01]
 [9.00000e+00 7.00000e+00 3.08400e+01 1.15100e+01 5.20000e+00 1.80000e+01
          nan 3.34000e+01 1.15600e+01 5.80000e-01]


In [40]:
# 40
print(grid.flatten())

[        nan 1.34000e+00 7.00000e+00 3.46300e+01 1.27600e+01 1.53000e+01
         nan 9.00000e+00 1.66000e+00 1.11000e+01         nan 1.44000e+00
 1.16300e+01 7.23100e+01 2.80000e+01 1.01600e+01 5.90000e-01 7.00000e+00
 2.53850e+02 4.20000e+00 5.08100e+01 8.01000e+00 6.79400e+01         nan
 3.27100e+01 5.41300e+02 6.91000e+00 3.08400e+01 3.51000e+00 4.34000e+00
 1.80000e+01 3.14400e+01 3.42000e+00 2.44600e+01 3.90000e+01 1.30000e+01
 3.00200e+01 1.15100e+01 6.30200e+01 1.03000e+00 2.90000e+00 3.92000e+00
 2.02200e+01 2.41500e+01 8.40000e+01         nan 2.70000e+01 5.20000e+00
 4.00000e+00 2.76000e+00 1.12600e+01 2.40000e+01 5.26000e+00 1.40000e+01
 5.00000e+00 1.14100e+01         nan 1.80000e+01 1.28000e+02 1.54000e+01
 1.90066e+03 4.00000e+00 3.00000e+00 9.00000e+00 1.33350e+02 1.29170e+03
 4.00000e+00         nan 2.00000e+00         nan 2.05100e+01 1.13300e+01
 5.99100e+01 1.00000e+00 2.29700e+01 0.00000e+00 2.49000e+01 3.34000e+01
 3.40000e+01 1.49200e+01 1.91700e+01 1.78600e+01 9.

In [41]:
# 41
combinedArray = np.concatenate([hours, rates])
print(combinedArray.shape)

(99176,)


In [42]:
# 42
parts = np.array_split(hours, 5)
for i, p in enumerate(parts):
    print(i, p.shape)

0 (9918,)
1 (9918,)
2 (9918,)
3 (9917,)
4 (9917,)


In [43]:
# 43
print(np.nanpercentile(hours, [25, 50, 75]))

[ 4.33  13.125 29.51 ]


In [44]:
# 44
print(np.cumsum(hours[:20]))

[nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan]


In [45]:
# 45
print(np.diff(hours))

[   nan   5.66  27.63 ... -42.    -3.     4.5 ]


In [46]:
# 46
print(np.clip(hours, 0, 100))

[ nan 1.34 7.   ... 5.   2.   6.5 ]


In [47]:
# 47
hours_int = np.nan_to_num(hours).astype(int)
print(hours_int)

[0 1 7 ... 5 2 6]


In [48]:
# 48
hours_copy = hours.copy()
hours_copy[0] = 999
print("Copy array: ", hours_copy[0])
print("Original array: ", hours[0])

Copy array:  999.0
Original array:  nan


In [49]:
# 49


In [50]:
# 50
print(np.nansum(hours * rates))

314745135.04269993
