In [1]:
# 1
import numpy as np


print(np.__version__)

2.1.3


In [10]:
# 2
import pandas as pd
df = pd.read_csv('it_services_tickets_raw.csv')
hours = df["hours_logged"].to_numpy()
print(hours)

['?' '1.34 ' '7' ... '5' '2' '6.5 hrs']


In [11]:
#3
print("Shape:", hours.shape)
print("Size:", hours.size)
print("Dtype:", hours.dtype)

Shape: (49588,)
Size: 49588
Dtype: object


In [12]:
#4
arr = np.arange(1, 51)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]


In [13]:
#5
print(np.linspace(0, 100, 10))

[  0.          11.11111111  22.22222222  33.33333333  44.44444444
  55.55555556  66.66666667  77.77777778  88.88888889 100.        ]


In [14]:
#6
print("Array with 10 zeros: ",np.zeros(10))
print("Array with 10 ones: " ,np.ones(10))

Array with 10 zeros:  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Array with 10 ones:  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [15]:
#7
np.random.seed(42)
print(np.random.rand(3, 3))

[[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]]


In [19]:
# 8
twoDimArray = df[["hours_logged", "Billing Rate (USD)"]].to_numpy()
print(twoDimArray)

[['?' '$39.45']
 ['1.34 ' '33.15']
 ['7' '48.10']
 ...
 ['5' '24.94']
 ['2' '$116.76']
 ['6.5 hrs' ' 89.02 ']]


In [20]:
# 9
print(twoDimArray.ndim)
print(hours.ndim)

2
1


In [21]:
# 10
print(hours[:5])

['?' '1.34 ' '7' '34.630' '12.76 ']


In [22]:
# 11
print(hours[-5:])

['4' '47' '5' '2' '6.5 hrs']


In [27]:
# 12
print(hours[:20:2])

['?' '7' '12.76 ' '--' '1.660' nan '11.63' '28' '0.59' '253.85']


In [28]:
# 13
print(hours[::-1])

['6.5 hrs' '2' '5' ... '7' '1.34 ' '?']


In [29]:
# 14
print(np.sum(hours))

TypeError: can only concatenate str (not "float") to str

In [34]:
# 15
hours = np.array(hours, dtype=float)

print("Mean:", np.mean(hours))
print("Min:", np.min(hours))
print("Max:", np.max(hours))

ValueError: could not convert string to float: '?'

In [33]:
# 16
print(np.std(hours))

TypeError: can only concatenate str (not "float") to str

In [38]:
# 17
hours = pd.to_numeric(pd.Series(hours), errors="coerce").to_numpy()
print(np.nanmedian(hours))

13.13


In [39]:
# 18
print(np.isnan(hours).sum())

12227


In [40]:
# 19
print(np.nanmean(hours))

63.614814913947704


In [41]:
# 20
hours_filled = np.nan_to_num(hours, nan=0.0)
print(hours_filled)

[0.   1.34 7.   ... 5.   2.   0.  ]


In [42]:
# 21
print((hours > 100).sum())

1633


In [43]:
# 22
print(hours[hours > 100])

[ 253.85  128.   1900.66 ...  562.22  141.9   137.56]


In [44]:
# 23
print(hours[(hours > 10) & (hours < 50)])

[34.63 12.76 15.3  ... 19.   25.23 47.  ]


In [45]:
# 24
print((hours<0).sum())

140


In [48]:
# 25
hours[hours<0]=0
print(hours)

[ nan 1.34 7.   ... 5.   2.    nan]


In [49]:
# 26
print(np.sort(hours))

[ 0.  0.  0. ... nan nan nan]


In [50]:
# 27
print(np.nanargmax(hours))

10080


In [52]:
# 28
np.sort(hours[~np.isnan(hours)])[::-1][:5]

array([9888.01, 9888.01, 8760.  , 8760.  , 8760.  ])

In [53]:
# 29
print(np.round(hours,1))

[nan 1.3 7.  ... 5.  2.  nan]


In [54]:
# 30
print(hours*2)

[  nan  2.68 14.   ... 10.    4.     nan]


In [55]:
# 31
print(hours+10)

[  nan 11.34 17.   ... 15.   12.     nan]


In [57]:
# 32
rates = df["Billing Rate (USD)"].to_numpy()
print(hours * rates)

TypeError: can't multiply sequence by non-int of type 'float'

In [58]:
# 33
print(len(hours) == len(rates))
print(hours.shape == rates.shape)

True
True


In [59]:
# 34
print(len(hours) == len(rates))
print(hours.shape == rates.shape)

True
True


In [61]:
# 35
speed = np.where(hours >24, "slow","fast")
print(speed)

['fast' 'fast' 'fast' ... 'fast' 'fast' 'fast']


In [66]:
# 36
priority = df["PRIORITY"].fillna("Unknown").to_numpy()
print(np.unique(priority))

[' ' '-' '--' '1' '2' '3' '4' '?' 'CRITICAL' 'Critical' 'HIGH' 'High'
 'LOW' 'Low' 'MEDIUM' 'Medium' 'P1' 'P1 - Critical' 'P2' 'P3' 'P4'
 'PRIORITY' 'Unknown' 'high' 'low' 'medium' 'missing' 'na' 'p1' 'p2' 'p3'
 'p4']


In [67]:
# 37
values, counts = np.unique(priority, return_counts=True)
print(values, counts)

[' ' '-' '--' '1' '2' '3' '4' '?' 'CRITICAL' 'Critical' 'HIGH' 'High'
 'LOW' 'Low' 'MEDIUM' 'Medium' 'P1' 'P1 - Critical' 'P2' 'P3' 'P4'
 'PRIORITY' 'Unknown' 'high' 'low' 'medium' 'missing' 'na' 'p1' 'p2' 'p3'
 'p4'] [  97  108  111 1992 2019 1995 1968   90 2047 2063 2005 2059 2002 1900
 2013 2015 1945 2044 1967 2010 1930    4  856 2029 2003 2072  128  132
 1993 1961 2069 1961]


In [68]:
# 38
grid = hours[:100].reshape(10, 10)
print(grid.shape)

(10, 10)


In [69]:
# 39
print(grid.T)

[[        nan         nan 5.08100e+01 1.80000e+01         nan 1.12600e+01
  1.90066e+03 2.05100e+01 1.91700e+01 1.30000e+01]
 [1.34000e+00 1.44000e+00 8.01000e+00 3.14400e+01 3.92000e+00 2.40000e+01
  4.00000e+00 1.13300e+01 1.78600e+01 1.09100e+01]
 [7.00000e+00 1.16300e+01 6.79400e+01 3.42000e+00 2.02200e+01 5.26000e+00
  3.00000e+00 5.99100e+01 9.21000e+00 8.00000e+00]
 [3.46300e+01 7.23100e+01         nan 2.44600e+01 2.41500e+01 1.40000e+01
  9.00000e+00 1.00000e+00 5.40000e+01 3.81000e+00]
 [1.27600e+01 2.80000e+01 3.27100e+01         nan 8.40000e+01 5.00000e+00
  1.33350e+02 2.29700e+01         nan 3.73680e+02]
 [1.53000e+01 1.01600e+01         nan 1.30000e+01         nan 1.14100e+01
          nan 0.00000e+00 2.00000e+01 1.13800e+01]
 [        nan 5.90000e-01 6.91000e+00 3.00200e+01 2.70000e+01         nan
  4.00000e+00         nan 6.00000e+00 3.36700e+01]
 [9.00000e+00 7.00000e+00 3.08400e+01 1.15100e+01         nan 1.80000e+01
          nan         nan 1.15600e+01 5.80000e-01]


In [70]:
# 40
print(grid.flatten())

[        nan 1.34000e+00 7.00000e+00 3.46300e+01 1.27600e+01 1.53000e+01
         nan 9.00000e+00 1.66000e+00         nan         nan 1.44000e+00
 1.16300e+01 7.23100e+01 2.80000e+01 1.01600e+01 5.90000e-01 7.00000e+00
 2.53850e+02 4.20000e+00 5.08100e+01 8.01000e+00 6.79400e+01         nan
 3.27100e+01         nan 6.91000e+00 3.08400e+01 3.51000e+00 4.34000e+00
 1.80000e+01 3.14400e+01 3.42000e+00 2.44600e+01         nan 1.30000e+01
 3.00200e+01 1.15100e+01 6.30200e+01 1.03000e+00         nan 3.92000e+00
 2.02200e+01 2.41500e+01 8.40000e+01         nan 2.70000e+01         nan
 4.00000e+00 2.76000e+00 1.12600e+01 2.40000e+01 5.26000e+00 1.40000e+01
 5.00000e+00 1.14100e+01         nan 1.80000e+01 1.28000e+02 1.54000e+01
 1.90066e+03 4.00000e+00 3.00000e+00 9.00000e+00 1.33350e+02         nan
 4.00000e+00         nan 2.00000e+00         nan 2.05100e+01 1.13300e+01
 5.99100e+01 1.00000e+00 2.29700e+01 0.00000e+00         nan         nan
 3.40000e+01 1.49200e+01 1.91700e+01 1.78600e+01 9.

In [71]:
# 41
combinedArray = np.concatenate([hours, rates])
print(combinedArray.shape)

(99176,)


In [72]:
# 42
parts = np.array_split(hours, 5)
for i, p in enumerate(parts):
    print(i, p.shape)

0 (9918,)
1 (9918,)
2 (9918,)
3 (9917,)
4 (9917,)


In [73]:
# 43
print(np.nanpercentile(hours, [25, 50, 75]))

[ 4.34 13.13 29.45]


In [74]:
# 44
print(np.cumsum(hours[:20]))

[nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan]


In [75]:
# 45
print(np.diff(hours))

[   nan   5.66  27.63 ... -42.    -3.      nan]


In [76]:
# 46
print(np.clip(hours, 0, 100))

[ nan 1.34 7.   ... 5.   2.    nan]


In [77]:
# 47
hours_int = np.nan_to_num(hours).astype(int)
print(hours_int)

[0 1 7 ... 5 2 0]


In [78]:
# 48
hours_copy = hours.copy()
hours_copy[0] = 999
print("Copy array: ", hours_copy[0])
print("Original array: ", hours[0])

Copy array:  999.0
Original array:  nan


In [ ]:
# 49


In [79]:
# 50
print(np.nansum(hours * rates))

TypeError: can't multiply sequence by non-int of type 'float'